# CMake generated Testfile for 
# Source directory: /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource
# Build directory: /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/resource
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(resources.ResourceTest.create_without_servicename "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/resource/resource_test" "--gtest_filter=ResourceTest.create_without_servicename")
set_tests_properties(resources.ResourceTest.create_without_servicename PROPERTIES  DEF_SOURCE_LINE "resource_test.cc:48" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;0;")
add_test(resources.ResourceTest.create_with_servicename "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/resource/resource_test" "--gtest_filter=ResourceTest.create_with_servicename")
set_tests_properties(resources.ResourceTest.create_with_servicename PROPERTIES  DEF_SOURCE_LINE "resource_test.cc:82" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;0;")
add_test(resources.ResourceTest.create_with_emptyatrributes "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/resource/resource_test" "--gtest_filter=ResourceTest.create_with_emptyatrributes")
set_tests_properties(resources.ResourceTest.create_with_emptyatrributes PROPERTIES  DEF_SOURCE_LINE "resource_test.cc:115" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;0;")
add_test(resources.ResourceTest.create_with_schemaurl "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/resource/resource_test" "--gtest_filter=ResourceTest.create_with_schemaurl")
set_tests_properties(resources.ResourceTest.create_with_schemaurl PROPERTIES  DEF_SOURCE_LINE "resource_test.cc:138" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;0;")
add_test(resources.ResourceTest.Merge "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/resource/resource_test" "--gtest_filter=ResourceTest.Merge")
set_tests_properties(resources.ResourceTest.Merge PROPERTIES  DEF_SOURCE_LINE "resource_test.cc:148" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;0;")
add_test(resources.ResourceTest.MergeEmptyString "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/resource/resource_test" "--gtest_filter=ResourceTest.MergeEmptyString")
set_tests_properties(resources.ResourceTest.MergeEmptyString PROPERTIES  DEF_SOURCE_LINE "resource_test.cc:168" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;0;")
add_test(resources.ResourceTest.MergeSchemaUrl "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/resource/resource_test" "--gtest_filter=ResourceTest.MergeSchemaUrl")
set_tests_properties(resources.ResourceTest.MergeSchemaUrl PROPERTIES  DEF_SOURCE_LINE "resource_test.cc:189" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;0;")
add_test(resources.ResourceTest.OtelResourceDetector "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/resource/resource_test" "--gtest_filter=ResourceTest.OtelResourceDetector")
set_tests_properties(resources.ResourceTest.OtelResourceDetector PROPERTIES  DEF_SOURCE_LINE "resource_test.cc:216" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;0;")
add_test(resources.ResourceTest.OtelResourceDetectorServiceNameOverride "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/resource/resource_test" "--gtest_filter=ResourceTest.OtelResourceDetectorServiceNameOverride")
set_tests_properties(resources.ResourceTest.OtelResourceDetectorServiceNameOverride PROPERTIES  DEF_SOURCE_LINE "resource_test.cc:238" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;0;")
add_test(resources.ResourceTest.OtelResourceDetectorEmptyEnv "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/resource/resource_test" "--gtest_filter=ResourceTest.OtelResourceDetectorEmptyEnv")
set_tests_properties(resources.ResourceTest.OtelResourceDetectorEmptyEnv PROPERTIES  DEF_SOURCE_LINE "resource_test.cc:262" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;0;")
add_test(resources.ResourceTest.DerivedResourceDetector "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/resource/resource_test" "--gtest_filter=ResourceTest.DerivedResourceDetector")
set_tests_properties(resources.ResourceTest.DerivedResourceDetector PROPERTIES  DEF_SOURCE_LINE "resource_test.cc:282" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/resource/CMakeLists.txt;0;")
