cc_test(
    name = "resource_test",
    srcs = [
        "resource_test.cc",
    ],
    tags = ["test"],
    deps = [
        "//api",
        "//sdk/src/resource",
        "@com_google_googletest//:gtest_main",
    ],
)
