cc_test(
    name = "timestamp_test",
    srcs = [
        "timestamp_test.cc",
    ],
    tags = [
        "api",
        "test",
    ],
    deps = [
        "//api",
        "@com_google_googletest//:gtest_main",
    ],
)
