# CMake generated Testfile for 
# Source directory: /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/metrics
# Build directory: /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/metrics
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(metrics_new.Provider.GetMeterProviderDefault "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/metrics/meter_provider_test" "--gtest_filter=Provider.GetMeterProviderDefault")
set_tests_properties(metrics_new.Provider.GetMeterProviderDefault PROPERTIES  DEF_SOURCE_LINE "meter_provider_test.cc:15" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/metrics/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/metrics/CMakeLists.txt;0;")
add_test(metrics_new.Provider.SetMeterProvider "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/metrics/meter_provider_test" "--gtest_filter=Provider.SetMeterProvider")
set_tests_properties(metrics_new.Provider.SetMeterProvider PROPERTIES  DEF_SOURCE_LINE "meter_provider_test.cc:21" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/metrics/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/metrics/CMakeLists.txt;0;")
add_test(metrics_new.Provider.MultipleMeterProviders "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/metrics/meter_provider_test" "--gtest_filter=Provider.MultipleMeterProviders")
set_tests_properties(metrics_new.Provider.MultipleMeterProviders PROPERTIES  DEF_SOURCE_LINE "meter_provider_test.cc:28" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/metrics/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/metrics/CMakeLists.txt;0;")
add_test(metrics_new.Counter.Add "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/metrics/noop_sync_instrument_test" "--gtest_filter=Counter.Add")
set_tests_properties(metrics_new.Counter.Add PROPERTIES  DEF_SOURCE_LINE "noop_sync_instrument_test.cc:16" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/metrics/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/metrics/CMakeLists.txt;0;")
add_test(metrics_new.histogram.Record "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/metrics/noop_sync_instrument_test" "--gtest_filter=histogram.Record")
set_tests_properties(metrics_new.histogram.Record PROPERTIES  DEF_SOURCE_LINE "noop_sync_instrument_test.cc:30" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/metrics/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/metrics/CMakeLists.txt;0;")
add_test(metrics_new.UpDownCountr.Record "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/metrics/noop_sync_instrument_test" "--gtest_filter=UpDownCountr.Record")
set_tests_properties(metrics_new.UpDownCountr.Record PROPERTIES  DEF_SOURCE_LINE "noop_sync_instrument_test.cc:42" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/metrics/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/metrics/CMakeLists.txt;0;")
