codecov:
  require_ci_to_pass: yes
  max_report_age: off

coverage:
  precision: 2
  round: down
  range: "80...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

fixes:
  - "/home/runner/::"
