version: 2
updates:
  - package-ecosystem: "bazel"
    directory: "/"
    schedule:
     interval: daily
    cooldown:
      default-days: 7

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
     interval: daily
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "GHA"
    cooldown:
      default-days: 7

