# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# see https://github.com/cncf/clomonitor/blob/main/docs/checks.md#exemptions
exemptions:
  - check: artifacthub_badge
    reason: "Artifact Hub doesn't support c++ packages"
