
# Please adjust to your needs (see https://www.gitpod.io/docs/config-gitpod-file)
# and commit this file to your remote git repository to share the goodness with others.

tasks:
  - init: sudo apt-get install -y libboost-all-dev && go install github.com/bazelbuild/bazelisk@latest
    command: bazelisk build //...


