

/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * DO NOT EDIT, this is an Auto-generated file from:
 * buildscripts/semantic-convention/templates/registry/semantic_attributes-h.j2
 */

#pragma once

#include "opentelemetry/common/macros.h"
#include "opentelemetry/version.h"

OPENTELEMETRY_BEGIN_NAMESPACE
namespace semconv
{
namespace az
{

/**
 * The unique identifier of the service request. It's generated by the Azure service and returned
 * with the response.
 */
static const char *kAzServiceRequestId = "az.service_request_id";

}  // namespace az
}  // namespace semconv
OPENTELEMETRY_END_NAMESPACE
