cc_binary(
    name = "validate",
    srcs = [
        "tracecontext_validate.cc",
    ],
    deps = [
        "//api",
        "//ext/src/tracecontext_validation",
        "//sdk/src/trace",
    ],
)