# TODO: enable bazel build
# cc_binary(
#     name = "example_jaeger",
#     srcs = [
#         "main.cc",
#     ],
#     deps = [
#         "//examples/common/foo_library:common_foo_library",
#         "//api",
#         "//exporters/jaeger:jaeger_exporter",
#         "//sdk/src/trace",
#     ],
# )
