# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# All components options

if(NOT DEFINED ENABLE_COMPONENTS)
    set(ENABLE_COMPONENTS ON)
endif()

set(OTELCPP_WITH_OTLP_GRPC ${ENABLE_COMPONENTS} CACHE BOOL "" FORCE)
set(OTELCPP_WITH_OTLP_HTTP ${ENABLE_COMPONENTS} CACHE BOOL "" FORCE)
set(OTELCPP_WITH_OTLP_FILE ${ENABLE_COMPONENTS} CACHE BOOL "" FORCE)

set(OTELCPP_WITH_PROMETHEUS ${ENABLE_COMPONENTS} CACHE BOOL "" FORCE)
set(OTELCPP_WITH_ZIPKIN ${ENABLE_COMPONENTS} CACHE BOOL "" FORCE)
set(OTELCPP_WITH_ELASTICSEARCH ${ENABLE_COMPONENTS} CACHE BOOL "" FORCE)

if(WIN32)
  set(OTELCPP_WITH_ETW ${ENABLE_COMPONENTS} CACHE BOOL "" FORCE)
endif()

if(OTELCPP_WITH_ABI_VERSION_1)
  set(OTELCPP_WITH_OPENTRACING ${ENABLE_COMPONENTS} CACHE BOOL "" FORCE)
endif()
