# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# All testing options

if(NOT DEFINED ENABLE_TESTS)
    set(ENABLE_TESTS ON)
endif()

set(OTELCPP_BUILD_TESTING ${ENABLE_TESTS} CACHE BOOL "" FORCE)
set(OTELCPP_BUILD_W3CTRACECONTEXT_TEST ${ENABLE_TESTS} CACHE BOOL "" FORCE)
set(OTELCPP_WITH_BENCHMARK ${ENABLE_TESTS} CACHE BOOL "" FORCE)
set(OTELCPP_WITH_FUNC_TESTS ${ENABLE_TESTS} CACHE BOOL "" FORCE)
