cc_test(
    name = "default_tracer_provider",
    srcs = [
        "default_tracer_provider_test.cc",
    ],
    deps = [
        "//sdk/src/trace",
        "@com_google_googletest//:gtest_main",
    ],
)
