cc_test(
    name = "random_test",
    srcs = [
        "random_test.cc",
    ],
    deps = [
        "//sdk/src/common:random",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "random_fork_test",
    srcs = [
        "random_fork_test.cc",
    ],
    deps = [
        "//sdk/src/common:random",
        "@com_google_googletest//:gtest_main",
    ],
)
