cc_test(
    name = "atomic_unique_ptr_test",
    srcs = [
        "atomic_unique_ptr_test.cc",
    ],
    deps = [
        "//sdk/src/common:atomic_unique_ptr",
        "@com_google_googletest//:gtest_main",
    ],
)

