# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

ARG BASE_IMAGE=ubuntu:26.04@sha256:3595d7fc4286a33fad0fd853a4063e654287a9c3787437d7937c94ca3f7a804e

FROM ${BASE_IMAGE} AS final

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y build-essential autoconf \
    libtool pkg-config cmake git libssl-dev

WORKDIR /work
