# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

ARG BASE_IMAGE=alpine:latest@sha256:4b7ce07002c69e8f3d704a9c5d6fd3053be500b7f1c69fc0d80990c2ad8dd412

FROM ${BASE_IMAGE} AS final

RUN apk update

RUN apk add --update alpine-sdk \
    && apk add cmake g++ \
    git autoconf libtool linux-headers \
    openssl openssl-dev \
    libevent-dev

WORKDIR /work
