# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

ARG BASE_IMAGE=alpine:3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

FROM ${BASE_IMAGE} AS final

RUN apk update

RUN apk add --update alpine-sdk \
    && apk add cmake g++ \
    git autoconf libtool linux-headers \
    openssl openssl-dev \
    libevent-dev

WORKDIR /work
