# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

ARG BASE_IMAGE=ubuntu:26.04@sha256:f144425ff09be612d6d9ad965196e9cdc23dae1f42110a8a11a3e9a8198759f7

FROM ${BASE_IMAGE} AS final

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y build-essential autoconf \
    libtool pkg-config cmake git libssl-dev

WORKDIR /work
