# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

ARG BASE_IMAGE=alpine:3.24.2@sha256:5b02b42e375f7426f8d65c3af331ca05d9878f9989230354504e0b9dfd431f60

FROM ${BASE_IMAGE} AS final

RUN apk update

RUN apk add --update alpine-sdk \
    && apk add cmake g++ \
    git autoconf libtool linux-headers \
    openssl openssl-dev \
    libevent-dev

WORKDIR /work
