# CMake generated Testfile for 
# Source directory: /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/core
# Build directory: /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/core
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(trace.SystemTimestampTest.Construction "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/core/timestamp_test" "--gtest_filter=SystemTimestampTest.Construction")
set_tests_properties(trace.SystemTimestampTest.Construction PROPERTIES  DEF_SOURCE_LINE "timestamp_test.cc:20" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/core/CMakeLists.txt;9;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/core/CMakeLists.txt;0;")
add_test(trace.SystemTimestampTest.Comparison "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/core/timestamp_test" "--gtest_filter=SystemTimestampTest.Comparison")
set_tests_properties(trace.SystemTimestampTest.Comparison PROPERTIES  DEF_SOURCE_LINE "timestamp_test.cc:33" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/core/CMakeLists.txt;9;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/core/CMakeLists.txt;0;")
add_test(trace.SteadyTimestampTest.Construction "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/core/timestamp_test" "--gtest_filter=SteadyTimestampTest.Construction")
set_tests_properties(trace.SteadyTimestampTest.Construction PROPERTIES  DEF_SOURCE_LINE "timestamp_test.cc:46" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/core/CMakeLists.txt;9;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/core/CMakeLists.txt;0;")
add_test(trace.SteadyTimestampTest.Comparison "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/core/timestamp_test" "--gtest_filter=SteadyTimestampTest.Comparison")
set_tests_properties(trace.SteadyTimestampTest.Comparison PROPERTIES  DEF_SOURCE_LINE "timestamp_test.cc:59" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/core/CMakeLists.txt;9;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/core/CMakeLists.txt;0;")
add_test(version.VersionTest.Consistency "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/core/version_test" "--gtest_filter=VersionTest.Consistency")
set_tests_properties(version.VersionTest.Consistency PROPERTIES  DEF_SOURCE_LINE "version_test.cc:11" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/core/CMakeLists.txt;17;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/core/CMakeLists.txt;0;")
