# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# SKIP_SCHEMA_VALIDATION: translation_strategy 'UnderscoreEscapingWithoutSuffixes' renamed to 'underscore_escaping_without_suffixes/development' in schema v1.0; C++ parser not yet updated

file_format: "1.0"

meter_provider:
  readers:
    - pull:
        exporter:
          prometheus/development:
            host: localhost
            port: 9464
            without_scope_info: false
            translation_strategy: UnderscoreEscapingWithoutSuffixes
