exporters:
  logging:
    loglevel: DEBUG
    sampling_initial: 200
    sampling_thereafter: 200
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        #cors_allowed_origins:
        #- '*'
processors:
  batch:
service:
  pipelines:
    traces:
      receivers:
      - otlp
      exporters:
      - logging
      processors: [batch]
    logs:
      receivers:
      - otlp
      exporters:
      - logging
      processors: [batch]
