# CMake generated Testfile for 
# Source directory: /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage
# Build directory: /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/baggage
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(baggage.BaggageTest.ValidateExtractHeader "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/baggage/baggage_test" "--gtest_filter=BaggageTest.ValidateExtractHeader")
set_tests_properties(baggage.BaggageTest.ValidateExtractHeader PROPERTIES  DEF_SOURCE_LINE "baggage_test.cc:54" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/CMakeLists.txt;10;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/CMakeLists.txt;0;")
add_test(baggage.BaggageTest.ValidateInjectHeader "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/baggage/baggage_test" "--gtest_filter=BaggageTest.ValidateInjectHeader")
set_tests_properties(baggage.BaggageTest.ValidateInjectHeader PROPERTIES  DEF_SOURCE_LINE "baggage_test.cc:115" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/CMakeLists.txt;10;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/CMakeLists.txt;0;")
add_test(baggage.BaggageTest.BaggageGet "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/baggage/baggage_test" "--gtest_filter=BaggageTest.BaggageGet")
set_tests_properties(baggage.BaggageTest.BaggageGet PROPERTIES  DEF_SOURCE_LINE "baggage_test.cc:142" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/CMakeLists.txt;10;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/CMakeLists.txt;0;")
add_test(baggage.BaggageTest.BaggageSet "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/baggage/baggage_test" "--gtest_filter=BaggageTest.BaggageSet")
set_tests_properties(baggage.BaggageTest.BaggageSet PROPERTIES  DEF_SOURCE_LINE "baggage_test.cc:159" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/CMakeLists.txt;10;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/CMakeLists.txt;0;")
add_test(baggage.BaggageTest.BaggageRemove "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/baggage/baggage_test" "--gtest_filter=BaggageTest.BaggageRemove")
set_tests_properties(baggage.BaggageTest.BaggageRemove PROPERTIES  DEF_SOURCE_LINE "baggage_test.cc:190" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/CMakeLists.txt;10;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/CMakeLists.txt;0;")
add_test(baggage.BaggageTest.BaggageGetAll "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/baggage/baggage_test" "--gtest_filter=BaggageTest.BaggageGetAll")
set_tests_properties(baggage.BaggageTest.BaggageGetAll PROPERTIES  DEF_SOURCE_LINE "baggage_test.cc:207" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/CMakeLists.txt;10;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/CMakeLists.txt;0;")
subdirs("propagation")
