/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef zipkincore_CONSTANTS_H
#define zipkincore_CONSTANTS_H

#include "zipkincore_types.h"

namespace twitter { namespace zipkin { namespace thrift {

class zipkincoreConstants {
 public:
  zipkincoreConstants();

  std::string CLIENT_SEND;
  std::string CLIENT_RECV;
  std::string SERVER_SEND;
  std::string SERVER_RECV;
  std::string MESSAGE_SEND;
  std::string MESSAGE_RECV;
  std::string WIRE_SEND;
  std::string WIRE_RECV;
  std::string CLIENT_SEND_FRAGMENT;
  std::string CLIENT_RECV_FRAGMENT;
  std::string SERVER_SEND_FRAGMENT;
  std::string SERVER_RECV_FRAGMENT;
  std::string LOCAL_COMPONENT;
  std::string CLIENT_ADDR;
  std::string SERVER_ADDR;
  std::string MESSAGE_ADDR;
};

extern const zipkincoreConstants g_zipkincore_constants;

}}} // namespace

#endif
