cc_test(
    name = "tracez_data_aggregator_tests",
    srcs = [
        "tracez_data_aggregator_tests.cc",
    ],
    deps = [
        "//sdk/src/trace",
        "//ext/src/zpages",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "tracez_processor_tests",
    srcs = [
        "tracez_processor_test.cc",
    ],
    deps = [
        "//sdk/src/trace",
        "//ext/src/zpages",
        "@com_google_googletest//:gtest_main",
    ],
)
