cc_test(
    name = "io_dispatcher_test",
    srcs = [
        "io_dispatcher_test.cc",
    ],
    linkstatic = 1,
    deps = [
        "//sdk/src/event/libevent:io_dispatcher",
        "@com_google_googletest//:gtest_main",
    ],
)
