cc_test(
    name = "controller_test",
    srcs = [
        "controller_test.cc",
    ],
    tags = [
        "metrics",
        "test",
    ],
    deps = [
        "//exporters/ostream:ostream_metrics_exporter_deprecated",
        "//sdk/src/_metrics:metrics_deprecated",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "gauge_aggregator_test",
    srcs = [
        "gauge_aggregator_test.cc",
    ],
    tags = [
        "metrics",
        "test",
    ],
    deps = [
        "//sdk/src/_metrics:metrics_deprecated",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "min_max_sum_count_aggregator_test",
    srcs = [
        "min_max_sum_count_aggregator_test.cc",
    ],
    tags = [
        "metrics",
        "test",
    ],
    deps = [
        "//sdk/src/_metrics:metrics_deprecated",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "meter_provider_sdk_test",
    srcs = [
        "meter_provider_sdk_test.cc",
    ],
    tags = [
        "metrics",
        "test",
    ],
    deps = [
        "//sdk/src/_metrics:metrics_deprecated",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "meter_test",
    srcs = [
        "meter_test.cc",
    ],
    tags = [
        "metrics",
        "test",
    ],
    deps = [
        "//sdk/src/_metrics:metrics_deprecated",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "counter_aggregator_test",
    srcs = [
        "counter_aggregator_test.cc",
    ],
    tags = [
        "metrics",
        "test",
    ],
    deps = [
        "//sdk/src/_metrics:metrics_deprecated",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "exact_aggregator_test",
    srcs = [
        "exact_aggregator_test.cc",
    ],
    tags = [
        "metrics",
        "test",
    ],
    deps = [
        "//sdk/src/_metrics:metrics_deprecated",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "histogram_aggregator_test",
    srcs = [
        "histogram_aggregator_test.cc",
    ],
    tags = [
        "metrics",
        "test",
    ],
    deps = [
        "//sdk/src/_metrics:metrics_deprecated",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "metric_instrument_test",
    srcs = [
        "metric_instrument_test.cc",
    ],
    tags = [
        "metrics",
        "test",
    ],
    deps = [
        "//sdk/src/_metrics:metrics_deprecated",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "sketch_aggregator_test",
    srcs = [
        "sketch_aggregator_test.cc",
    ],
    tags = [
        "metrics",
        "test",
    ],
    deps = [
        "//sdk/src/_metrics:metrics_deprecated",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "ungrouped_processor_test",
    srcs = [
        "ungrouped_processor_test.cc",
    ],
    tags = [
        "metrics",
        "test",
    ],
    deps = [
        "//sdk/src/_metrics:metrics_deprecated",
        "@com_google_googletest//:gtest_main",
    ],
)
