# CMake generated Testfile for 
# Source directory: /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/trace/propagation/detail
# Build directory: /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/trace/propagation/detail
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(trace.HexTest.ConvertOddLength "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/trace/propagation/detail/hex_test" "--gtest_filter=HexTest.ConvertOddLength")
set_tests_properties(trace.HexTest.ConvertOddLength PROPERTIES  DEF_SOURCE_LINE "hex_test.cc:13" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/trace/propagation/detail/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/trace/propagation/detail/CMakeLists.txt;0;")
add_test(trace.HexTest.ConvertEvenLength "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/trace/propagation/detail/hex_test" "--gtest_filter=HexTest.ConvertEvenLength")
set_tests_properties(trace.HexTest.ConvertEvenLength PROPERTIES  DEF_SOURCE_LINE "hex_test.cc:29" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/trace/propagation/detail/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/trace/propagation/detail/CMakeLists.txt;0;")
add_test(trace.*/SplitStringTestFixture.SplitsAsExpected/* "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/trace/propagation/detail/string_test" "--gtest_filter=*/SplitStringTestFixture.SplitsAsExpected/*")
set_tests_properties(trace.*/SplitStringTestFixture.SplitsAsExpected/* PROPERTIES  DEF_SOURCE_LINE "string_test.cc:51" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/trace/propagation/detail/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/trace/propagation/detail/CMakeLists.txt;0;")
