cc_test(
    name = "string_view_test",
    srcs = [
        "string_view_test.cc",
    ],
    deps = [
        "//api:api",
        "//3rd_party/catch2:catch2_with_main",
    ],
)

cc_test(
    name = "string_view_test2",
    srcs = [
        "string_view_test2.cc",
    ],
    deps = [
        "//api:api",
        "@com_google_googletest//:gtest_main",
    ],
)
