# CMake generated Testfile for 
# Source directory: /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/context/propagation
# Build directory: /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/context/propagation
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(trace.CompositePropagatorTest.Extract "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/context/propagation/composite_propagator_test" "--gtest_filter=CompositePropagatorTest.Extract")
set_tests_properties(trace.CompositePropagatorTest.Extract PROPERTIES  DEF_SOURCE_LINE "composite_propagator_test.cc:83" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/context/propagation/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/context/propagation/CMakeLists.txt;0;")
add_test(trace.CompositePropagatorTest.Inject "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/context/propagation/composite_propagator_test" "--gtest_filter=CompositePropagatorTest.Inject")
set_tests_properties(trace.CompositePropagatorTest.Inject PROPERTIES  DEF_SOURCE_LINE "composite_propagator_test.cc:123" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/context/propagation/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/context/propagation/CMakeLists.txt;0;")
