cc_test(
    name = "meter_provider_sdk_test",
    srcs = [
        "meter_provider_sdk_test.cc",
    ],
    deps = [
        "//sdk/src/metrics",
        "//sdk/src/resource",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "attributes_processor_test",
    srcs = [
        "attributes_processor_test.cc",
    ],
    deps = [
        "//sdk/src/metrics",
        "@com_google_googletest//:gtest_main",
    ],
)
