cc_test(
    name = "gauge_aggregator_test",
    srcs = [
        "gauge_aggregator_test.cc",
    ],
    deps = [
        "//sdk/src/metrics",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "min_max_sum_count_aggregator_test",
    srcs = [
        "min_max_sum_count_aggregator_test.cc",
    ],
    deps = [
        "//sdk/src/metrics",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "meter_provider_sdk_test",
    srcs = [
        "meter_provider_sdk_test.cc",
    ],
    deps = [
        "//sdk/src/metrics",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "counter_aggregator_test",
    srcs = [
        "counter_aggregator_test.cc",
    ],
    deps = [
        "//sdk/src/metrics",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "exact_aggregator_test",
    srcs = [
        "exact_aggregator_test.cc",
    ],
    deps = [
        "//sdk/src/metrics",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "histogram_aggregator_test",
    srcs = [
        "histogram_aggregator_test.cc",
    ],
    deps = [
        "//sdk/src/metrics",
        "@com_google_googletest//:gtest_main",
    ],
)
