# CMake generated Testfile for 
# Source directory: /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/propagation
# Build directory: /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/baggage/propagation
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(baggage.BaggagePropagatorTest.ExtractNoBaggageHeader "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/baggage/propagation/baggage_propagator_test" "--gtest_filter=BaggagePropagatorTest.ExtractNoBaggageHeader")
set_tests_properties(baggage.BaggagePropagatorTest.ExtractNoBaggageHeader PROPERTIES  DEF_SOURCE_LINE "baggage_propagator_test.cc:47" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/propagation/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/propagation/CMakeLists.txt;0;")
add_test(baggage.BaggagePropagatorTest.ExtractAndInjectBaggage "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/baggage/propagation/baggage_propagator_test" "--gtest_filter=BaggagePropagatorTest.ExtractAndInjectBaggage")
set_tests_properties(baggage.BaggagePropagatorTest.ExtractAndInjectBaggage PROPERTIES  DEF_SOURCE_LINE "baggage_propagator_test.cc:57" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/propagation/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/propagation/CMakeLists.txt;0;")
add_test(baggage.BaggagePropagatorTest.InjectEmptyHeader "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/api/test/baggage/propagation/baggage_propagator_test" "--gtest_filter=BaggagePropagatorTest.InjectEmptyHeader")
set_tests_properties(baggage.BaggagePropagatorTest.InjectEmptyHeader PROPERTIES  DEF_SOURCE_LINE "baggage_propagator_test.cc:96" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/propagation/CMakeLists.txt;8;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/api/test/baggage/propagation/CMakeLists.txt;0;")
