# CMake generated Testfile for 
# Source directory: /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/instrumentationscope
# Build directory: /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/instrumentationscope
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(instrumentationscope.InstrumentationScope.CreateInstrumentationScope "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/instrumentationscope/instrumentationscope_test" "--gtest_filter=InstrumentationScope.CreateInstrumentationScope")
set_tests_properties(instrumentationscope.InstrumentationScope.CreateInstrumentationScope PROPERTIES  DEF_SOURCE_LINE "instrumentationscope_test.cc:24" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/instrumentationscope/CMakeLists.txt;10;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/instrumentationscope/CMakeLists.txt;0;")
add_test(instrumentationscope.InstrumentationScope.CreateInstrumentationScopeWithLoopForAttributes "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/instrumentationscope/instrumentationscope_test" "--gtest_filter=InstrumentationScope.CreateInstrumentationScopeWithLoopForAttributes")
set_tests_properties(instrumentationscope.InstrumentationScope.CreateInstrumentationScopeWithLoopForAttributes PROPERTIES  DEF_SOURCE_LINE "instrumentationscope_test.cc:64" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/instrumentationscope/CMakeLists.txt;10;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/instrumentationscope/CMakeLists.txt;0;")
add_test(instrumentationscope.InstrumentationScope.CreateInstrumentationScopeWithKeyValueIterableAttributes "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/instrumentationscope/instrumentationscope_test" "--gtest_filter=InstrumentationScope.CreateInstrumentationScopeWithKeyValueIterableAttributes")
set_tests_properties(instrumentationscope.InstrumentationScope.CreateInstrumentationScopeWithKeyValueIterableAttributes PROPERTIES  DEF_SOURCE_LINE "instrumentationscope_test.cc:107" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/instrumentationscope/CMakeLists.txt;10;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/instrumentationscope/CMakeLists.txt;0;")
add_test(instrumentationscope.InstrumentationScope.SetAttribute "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/instrumentationscope/instrumentationscope_test" "--gtest_filter=InstrumentationScope.SetAttribute")
set_tests_properties(instrumentationscope.InstrumentationScope.SetAttribute PROPERTIES  DEF_SOURCE_LINE "instrumentationscope_test.cc:154" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/instrumentationscope/CMakeLists.txt;10;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/instrumentationscope/CMakeLists.txt;0;")
add_test(instrumentationscope.InstrumentationScope.LegacyInstrumentationLibrary "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/instrumentationscope/instrumentationscope_test" "--gtest_filter=InstrumentationScope.LegacyInstrumentationLibrary")
set_tests_properties(instrumentationscope.InstrumentationScope.LegacyInstrumentationLibrary PROPERTIES  DEF_SOURCE_LINE "instrumentationscope_test.cc:198" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/instrumentationscope/CMakeLists.txt;10;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/instrumentationscope/CMakeLists.txt;0;")
add_test(instrumentationscope.InstrumentationScope.Equal "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/instrumentationscope/instrumentationscope_test" "--gtest_filter=InstrumentationScope.Equal")
set_tests_properties(instrumentationscope.InstrumentationScope.Equal PROPERTIES  DEF_SOURCE_LINE "instrumentationscope_test.cc:213" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/instrumentationscope/CMakeLists.txt;10;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/instrumentationscope/CMakeLists.txt;0;")
add_test(instrumentationscope.InstrumentationScope.OperatorEqual "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/sdk/test/instrumentationscope/instrumentationscope_test" "--gtest_filter=InstrumentationScope.OperatorEqual")
set_tests_properties(instrumentationscope.InstrumentationScope.OperatorEqual PROPERTIES  DEF_SOURCE_LINE "instrumentationscope_test.cc:265" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/instrumentationscope/CMakeLists.txt;10;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/sdk/test/instrumentationscope/CMakeLists.txt;0;")
