# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# otel_add_header_probes(TARGET <name> LINK <target>... HEADERS <header>...)
#
# Adds a compile-only target that includes each header in a translation unit of
# its own, where that header is the only include. Combining headers in one
# translation unit cannot show that each of them stands on its own, because an
# include earlier in the file supplies whatever a later header is missing.
#
# The headers are listed explicitly rather than globbed so that renaming or
# removing an installed header fails here.
function(otel_add_header_probes)
  set(oneValueArgs TARGET)
  set(multiValueArgs LINK HEADERS)
  cmake_parse_arguments(OTEL_PROBES "" "${oneValueArgs}" "${multiValueArgs}"
                        ${ARGN})

  if(NOT OTEL_PROBES_TARGET)
    message(FATAL_ERROR "otel_add_header_probes: TARGET is required")
  endif()

  if(NOT OTEL_PROBES_HEADERS)
    message(FATAL_ERROR "otel_add_header_probes: HEADERS is required")
  endif()

  if(OTEL_PROBES_UNPARSED_ARGUMENTS)
    message(
      FATAL_ERROR
        "otel_add_header_probes: unknown arguments: ${OTEL_PROBES_UNPARSED_ARGUMENTS}"
    )
  endif()

  if(OTEL_PROBES_KEYWORDS_MISSING_VALUES)
    message(
      FATAL_ERROR
        "otel_add_header_probes: no values given for: ${OTEL_PROBES_KEYWORDS_MISSING_VALUES}"
    )
  endif()

  set(_probe_sources)
  foreach(_header IN LISTS OTEL_PROBES_HEADERS)
    string(MAKE_C_IDENTIFIER "${_header}" _probe_name)
    set(_probe_source
        "${CMAKE_CURRENT_BINARY_DIR}/header_probes/${_probe_name}.cc")
    # MAKE_C_IDENTIFIER maps every character outside [A-Za-z0-9_] to the same
    # underscore, so two header paths can produce one file name. Without this
    # check the second would overwrite the first and its probe would disappear.
    if(_probe_source IN_LIST _probe_sources)
      message(
        FATAL_ERROR
          "otel_add_header_probes: ${_header} and an earlier header both map to ${_probe_source}"
      )
    endif()
    # Include the header twice so that a missing or broken include guard is
    # reported wherever including it a second time would be ill-formed.
    file(WRITE "${_probe_source}"
         "// Generated by otel_add_header_probes(). Do not edit.\n"
         "#include <${_header}>\n" "#include <${_header}>\n")
    list(APPEND _probe_sources "${_probe_source}")
  endforeach()

  add_library(${OTEL_PROBES_TARGET} OBJECT ${_probe_sources})
  target_link_libraries(${OTEL_PROBES_TARGET} PRIVATE ${OTEL_PROBES_LINK})

  # A unity build would merge the probes back into a single translation unit,
  # which is exactly what this target exists to avoid.
  set_target_properties(${OTEL_PROBES_TARGET} PROPERTIES UNITY_BUILD OFF)
endfunction()
