# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

set(OTELCPP_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/..")
get_filename_component(OTELCPP_SOURCE_DIR "${OTELCPP_SOURCE_DIR}" ABSOLUTE)
set(OTELCPP_API_VERSION_FILE "${OTELCPP_SOURCE_DIR}/api/include/opentelemetry/version.h")

file(READ "${OTELCPP_API_VERSION_FILE}"
     OPENTELEMETRY_CPP_HEADER_VERSION_H)

if(NOT DEFINED OPENTELEMETRY_CPP_HEADER_VERSION_H)
      message(FATAL_ERROR "${OTELCPP_API_VERSION_FILE} not found")
endif()

if(OPENTELEMETRY_CPP_HEADER_VERSION_H MATCHES
   "OPENTELEMETRY_VERSION[ \t\r\n]+\"?([^\"]+)\"?")
  set(OPENTELEMETRY_VERSION ${CMAKE_MATCH_1})
else()
  message(
    FATAL_ERROR
      "OPENTELEMETRY_VERSION not found on ${OTELCPP_API_VERSION_FILE}"
 )
endif()

if(OPENTELEMETRY_CPP_HEADER_VERSION_H MATCHES "OPENTELEMETRY_ABI_VERSION_NO[ \t\r\n]+\"?([0-9]+)\"?")
   math(EXPR OPENTELEMETRY_ABI_VERSION_DEFAULT ${CMAKE_MATCH_1})
endif()

if(NOT OPENTELEMETRY_VERSION OR OPENTELEMETRY_VERSION VERSION_LESS_EQUAL "0.0.0")
  message(FATAL_ERROR "Failed to extract OpenTelemetry C++ version (${OPENTELEMETRY_VERSION}) from ${OTELCPP_API_VERSION_FILE}")
endif()

if(NOT OPENTELEMETRY_ABI_VERSION_DEFAULT)
  message(FATAL_ERROR "Failed to extract OpenTelemetry C++ ABI version from ${OTELCPP_API_VERSION_FILE}")
endif()
