# CMake generated Testfile for 
# Source directory: /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/memory
# Build directory: /home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/exporters/memory
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(exporter.InMemorySpanData.AddRecordable "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/exporters/memory/in_memory_span_data_test" "--gtest_filter=InMemorySpanData.AddRecordable")
set_tests_properties(exporter.InMemorySpanData.AddRecordable PROPERTIES  DEF_SOURCE_LINE "test/in_memory_span_data_test.cc:15" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/memory/CMakeLists.txt;76;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/memory/CMakeLists.txt;0;")
add_test(exporter.InMemorySpanExporter.ExportBatch "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/exporters/memory/in_memory_span_exporter_test" "--gtest_filter=InMemorySpanExporter.ExportBatch")
set_tests_properties(exporter.InMemorySpanExporter.ExportBatch PROPERTIES  DEF_SOURCE_LINE "test/in_memory_span_exporter_test.cc:18" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/memory/CMakeLists.txt;80;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/memory/CMakeLists.txt;0;")
add_test(exporter.InMemoryMetricDataTest.CircularBuffer "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/exporters/memory/in_memory_metric_data_test" "--gtest_filter=InMemoryMetricDataTest.CircularBuffer")
set_tests_properties(exporter.InMemoryMetricDataTest.CircularBuffer PROPERTIES  DEF_SOURCE_LINE "test/in_memory_metric_data_test.cc:30" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/memory/CMakeLists.txt;84;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/memory/CMakeLists.txt;0;")
add_test(exporter.InMemoryMetricDataTest.SimpleAggregate "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/exporters/memory/in_memory_metric_data_test" "--gtest_filter=InMemoryMetricDataTest.SimpleAggregate")
set_tests_properties(exporter.InMemoryMetricDataTest.SimpleAggregate PROPERTIES  DEF_SOURCE_LINE "test/in_memory_metric_data_test.cc:39" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/memory/CMakeLists.txt;84;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/memory/CMakeLists.txt;0;")
add_test(exporter.InMemoryMetricExporterTest.Export "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/exporters/memory/in_memory_metric_exporter_test" "--gtest_filter=InMemoryMetricExporterTest.Export")
set_tests_properties(exporter.InMemoryMetricExporterTest.Export PROPERTIES  DEF_SOURCE_LINE "test/in_memory_metric_exporter_test.cc:40" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/memory/CMakeLists.txt;88;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/memory/CMakeLists.txt;0;")
add_test(exporter.InMemoryMetricExporterTest.ForceFlush "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/exporters/memory/in_memory_metric_exporter_test" "--gtest_filter=InMemoryMetricExporterTest.ForceFlush")
set_tests_properties(exporter.InMemoryMetricExporterTest.ForceFlush PROPERTIES  DEF_SOURCE_LINE "test/in_memory_metric_exporter_test.cc:49" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/memory/CMakeLists.txt;88;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/memory/CMakeLists.txt;0;")
add_test(exporter.InMemoryMetricExporterTest.Shutdown "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/exporters/memory/in_memory_metric_exporter_test" "--gtest_filter=InMemoryMetricExporterTest.Shutdown")
set_tests_properties(exporter.InMemoryMetricExporterTest.Shutdown PROPERTIES  DEF_SOURCE_LINE "test/in_memory_metric_exporter_test.cc:54" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/memory/CMakeLists.txt;88;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/memory/CMakeLists.txt;0;")
add_test(exporter.InMemoryMetricExporterTest.TemporalitySelector "/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/_codeql_build_dir/exporters/memory/in_memory_metric_exporter_test" "--gtest_filter=InMemoryMetricExporterTest.TemporalitySelector")
set_tests_properties(exporter.InMemoryMetricExporterTest.TemporalitySelector PROPERTIES  DEF_SOURCE_LINE "test/in_memory_metric_exporter_test.cc:60" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/memory/CMakeLists.txt;88;gtest_add_tests;/home/runner/work/opentelemetry-cpp/opentelemetry-cpp/exporters/memory/CMakeLists.txt;0;")
