cc_binary(
    name = "example_w3c_tracecontext_test",
    srcs = [
        "main.cc",
    ],
    deps = [
        "//api",
        "//exporters/ostream:ostream_span_exporter",
        "//sdk/src/trace",
        "//ext:headers",
        "@curl",
    ],
)
