name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  cmake_test:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo ./ci/setup_cmake.sh ./ci/setup_ci_environment.sh
    - name: run tests
      run: ./ci/do_ci.sh cmake.test

  plugin_test:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo ./ci/setup_cmake.sh ./ci/setup_ci_environment.sh
    - name: run tests
      run: ./ci/do_ci.sh cmake.test_example_plugin
  
  gcc_48_test:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo ./ci/setup_ci_environment.sh ./ci/install_bazelisk.sh ./ci/install_gcc48.sh
    - name: run tests
      run: ./ci/do_ci.sh bazel.legacy.test
      
  bazel_test:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo ./ci/setup_cmake.sh ./ci/setup_ci_environment.sh ./ci/install_bazelisk.sh
    - name: run tests
      run: ./ci/do_ci.sh bazel.test

  bazel_noexcept:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo ./ci/setup_cmake.sh ./ci/setup_ci_environment.sh ./ci/install_bazelisk.sh
    - name: run tests
      run: ./ci/do_ci.sh bazel.noexcept

  bazel_asan:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo ./ci/setup_cmake.sh ./ci/setup_ci_environment.sh ./ci/install_bazelisk.sh
    - name: run tests
      run: ./ci/do_ci.sh bazel.asan

  bazel_tsan:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo ./ci/setup_cmake.sh ./ci/setup_ci_environment.sh ./ci/install_bazelisk.sh
    - name: run tests
      run: ./ci/do_ci.sh bazel.tsan

  benchmark:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo ./ci/setup_cmake.sh ./ci/setup_ci_environment.sh ./ci/install_bazelisk.sh
    - name: run tests
      run: ./ci/do_ci.sh benchmark


  format:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo ./ci/install_format_tools.sh
    - name: run tests
      run: ./ci/do_ci.sh bazel.test

  osx_test:
    
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: run tests
      run: ./ci/do_ci.sh bazel.test

  windows:
    
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: ./ci/setup_windows_cmake.ps1 ./ci/setup_windows_ci_environment.ps1 ./ci/install_windows_protobuf.ps1
      timeout-minutes: 15
    - name: run cmake test
      run: ./ci/do_ci.ps1 cmake.test
    - name: run otprotocol test
      run: ./ci/do_ci.sh cmake.exporter.otprotocol.test

  windows_bazel:
    
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: ./ci/install_windows_bazelisk.ps1
    - name: run tests
      run: ./ci/do_ci.ps1 bazel.build

  windows_plugin_test:
    
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: ./ci/setup_windows_cmake.ps1 ./ci/setup_windows_ci_environment.ps1
    - name: run tests
      run: ./ci/do_ci.ps1 cmake.test_example_plugin

   
