name: Clear Bazel MacOS Cache
on:
  workflow_dispatch:

jobs:
  clear-cache:
    runs-on: macos-latest
    steps:
      - name: Create empty Bazel cache dir
        run: rm -rf /Users/runner/.cache/bazel && mkdir -p /Users/runner/.cache/bazel

      - name: Save empty cache over old one
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: /Users/runner/.cache/bazel
          key: bazel_osx
