name: cppcheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  cppcheck:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          submodules: 'recursive'

      - name: Set up dependencies
        run: |
          sudo apt update -y
          sudo apt install -y cppcheck

      - name: Run cppcheck
        run: |
          cppcheck --version | tee cppcheck.log
          cppcheck \
            --force \
            --enable=warning,performance,portability \
            --inline-suppr \
            --suppress=unknownMacro:exporters/etw/include/opentelemetry/exporters/etw/TraceLoggingDynamic.h \
            --language=c++ \
            --std=c++17 \
            -I api/include \
            -I exporters/elasticsearch/include \
            -I exporters/etw/include \
            -I exporters/memory/include \
            -I exporters/ostream/include \
            -I exporters/otlp/include \
            -I exporters/prometheus/include \
            -I exporters/zipkin/include \
            -I ext/include \
            -I opentracing-shim/include \
            -I resource_detectors/include \
            -I sdk/include \
            -i build \
            -i test \
            -i third_party \
            -i tools \
            -j $(nproc) \
            . 2>&1 | tee --append cppcheck.log

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: success() || failure()
        with:
          name: Logs (cppcheck)
          path: ./cppcheck.log

      - name: Count warnings
        run: |
          set +e
          readonly WARNING_COUNT=`grep -c -E "\[.+\]" cppcheck.log`
          echo "cppcheck reported ${WARNING_COUNT} warning(s)"
          if [ $WARNING_COUNT -gt 0 ] ; then
            echo "::warning::cppcheck reported ${WARNING_COUNT} warning(s)"
            exit 1
          fi
