cc_binary(
    name = "metrics_simple_example",
    srcs = [
        "main.cc",
    ],
    deps = [
        "//api",
        "//sdk/src/metrics",
        "//exporters/ostream:ostream_metrics_exporter",
    ],
)
