cc_test(
    name = "dispatcher_test",
    srcs = [
        "dispatcher_test.cc",
    ],
    linkstatic = 1,
    deps = [
        "//sdk/src/event/async_timer:dispatcher",
        "@com_google_googletest//:gtest_main",
    ],
)
